[project]
name = "qubics-py"
version = "0.0.1"
dependencies = [
  "watchdog",
  "pyobjc-framework-Metal",
  "pyobjc-framework-MetalKit",
  "pyobjc-framework-Cocoa",
  "mlx",
  "numpy"
]
requires-python = ">=3.12"

[tool.pyright]
venvPath = "."
venv = ".venv"
exclude = ["build", "dist", ".venv", "__pycache__"]

[[tool.pyright.executionEnvironments]]
root = "src/rendering/"
reportAttributeAccessIssue = false
reportOptionalMemberAccess = false

[[tool.pyright.executionEnvironments]]
root = "src/alt/metal/deps.py"
reportAttributeAccessIssue = false
reportOptionalMemberAccess = false
