use std::fs;
use std::path::{Path};

fn main() {
    let generated_dir = "src/generated";
    generate_mod_file(generated_dir);
    println!("cargo:rerun-if-changed={}", generated_dir);
}

fn generate_mod_file(generated_dir: &str) {
    let mut mod_content = String::from("// This file is auto-generated by build.rs\n\n");

    if let Ok(entries) = fs::read_dir(generated_dir) {
        let mut modules: Vec<String> = entries
            .filter_map(|entry| {
                let path = entry.ok()?.path();
                if path.extension().map_or(false, |ext| ext == "rs") {
                    let filename = path.file_stem()?.to_string_lossy();
                    if filename != "mod" {
                        Some(filename.to_string())
                    } else {
                        None
                    }
                } else {
                    None
                }
            })
            .collect();

        modules.sort();

        for module in modules {
            mod_content.push_str(&format!("pub mod {};\n", module));
        }
    }

    let mod_path = Path::new(generated_dir).join("mod.rs");
    fs::write(&mod_path, mod_content).expect("Failed to write mod.rs");
}
