from typing import Any, TypeVar, Type

T = TypeVar('T', bound='NSObject')

class NSObject:
    @classmethod
    def alloc(cls: Type[T]) -> T: ...
    def init(self: T) -> T: ...

def NSMakeRect(x: Any, y: Any, w: Any, h: Any) -> Any: ...

NSWindowStyleMaskTitled = Any
NSWindowStyleMaskClosable = Any
NSWindowStyleMaskResizable = Any
NSWindowStyleMaskMiniaturizable = Any
NSBackingStoreBuffered = Any
NSApplicationActivationPolicyRegular = Any
NSWindowWillCloseNotification = Any

class NSMenu(NSObject):
    def init(self) -> 'NSMenu': ...
    def addItem_(self, item: Any) -> None: ...

class NSMenuItem(NSObject):
    def initWithTitle_action_keyEquivalent_(self, title: str, action: str, key: str) -> 'NSMenuItem': ...
    def setSubmenu_(self, menu: Any) -> None: ...

class NSWindow(NSObject):
    def initWithContentRect_styleMask_backing_defer_(self, rect: Any, style: Any, backing: Any, defer: bool) -> 'NSWindow': ...
    def makeKeyAndOrderFront_(self, arg: Any) -> None: ...
    def setContentView_(self, view: Any) -> None: ...
    def center(self) -> None: ...

class NSNotificationCenter(NSObject):
    @classmethod
    def defaultCenter(cls) -> 'NSNotificationCenter': ...
    def addObserver_selector_name_object_(self, observer: Any, selector: Any, name: Any, obj: Any) -> None: ...

class NSApplication(NSObject):
    @classmethod
    def sharedApplication(cls) -> 'NSApplication': ...
    def setActivationPolicy_(self, policy: Any) -> None: ...
    def activateIgnoringOtherApps_(self, flag: bool) -> None: ...
    def setMainMenu_(self, menu: Any) -> None: ...
    def setDelegate_(self, delegate: Any) -> None: ...
    def run(self) -> None: ...
    def terminate_(self, sender: Any) -> None: ...
