from typing import Any, Callable, TypeVar, Type

T = TypeVar('T')

def MTLCreateSystemDefaultDevice() -> Any: ...

def MTLClearColorMake(r: float, g: float, b: float, a: float) -> Any: ...
def MTLSizeMake(n: int, i: int, j: int) -> Any: ...

class MTLDevice:
    def newLibraryWithURL_error_(self, url: Any, err: Any) -> tuple[Any, Any]: ...
    def newRenderPipelineStateWithDescriptor_error_(self, descriptor: Any, err: Any) -> tuple[Any, Any]: ...
    def newCommandQueue(self) -> Any: ...

class MTLLibrary:
    def newFunctionWithName_(self, name: str) -> Any: ...

class MTLRenderPipelineDescriptor:
    @classmethod
    def alloc(cls: Type[T]) -> T: ...
    def init(self: T) -> T: ...
    def setVertexFunction_(self, fn: Any) -> None: ...
    def setFragmentFunction_(self, fn: Any) -> None: ...
    def setVertexDescriptor_(self, vd: Any) -> None: ...
    def colorAttachments(self) -> Any: ...

class MTLVertexDescriptor:
    @classmethod
    def alloc(cls: Type[T]) -> T: ...
    def init(self: T) -> T: ...
    def attributes(self) -> Any: ...
    def layouts(self) -> Any: ...

class MTLRenderPipelineState: ...

MTLPrimitiveTypeTriangle = Any
MTLResourceStorageModeShared = Any
MTLVertexStepFunctionPerVertex = Any
MTLVertexFormatFloat2 = Any
MTLVertexFormatFloat3 = Any
MTLPixelFormatBGRA8Unorm = Any
MTLBlendOperationAdd = Any
MTLBlendFactorSourceAlpha = Any
MTLBlendFactorOneMinusSourceAlpha = Any
