[project]
name = "qubics-py"
version = "0.0.1"
dependencies = [
  "watchdog",
  "pyobjc-framework-Metal",
  "pyobjc-framework-MetalKit",
  "pyobjc-framework-Cocoa",
  "pyobjc-framework-Quartz",
  "numpy",
  "toml",
  "flatbuffers==25.12.19",
  "fastapi==0.128.0",
  "uvicorn==0.40.0",
]
requires-python = ">=3.12"

[project.optional-dependencies]
dev = [
  "ty>=0.0.14"
]

[tool.ty.environment]
extra-paths = ["typings"]

