from typing import Any, TypeVar, Type

T = TypeVar('T')

class MTKView:
    @classmethod
    def alloc(cls: Type[T]) -> T: ...
    def initWithFrame_device_(self, frame: Any, device: Any) -> 'MTKView': ...
    def bounds(self): ...
    def addTrackingArea_(self, area): ...
    def drawableSize(self) -> tuple[int, int]: ...
    def setColorPixelFormat_(self, fmt: Any) -> None: ...
    def setClearColor_(self, color: Any) -> None: ...
    def setPaused_(self, val: bool) -> None: ...
    def setEnableSetNeedsDisplay_(self, val: bool) -> None: ...
    def setPreferredFramesPerSecond_(self, fps: int) -> None: ...
    def setDelegate_(self, delegate: Any) -> None: ...
    def currentDrawable(self) -> Any: ...
