include "units.fbs";

namespace q_generated.components;

table Transform2D {
  matrices: [units.Matrix3x3];  
}

table Transform3D {
  matrices: [units.Matrix4x4];  
}

table Shape {
  vertices: [units.Vector2];  
  colors: [units.Color];      
}

table Mesh {
  vertices: [units.Vector4];  
  colors: [units.Color];      
}

table PerspectiveCamera {
  fov: [float];  
}

table OrthographicCamera {
  size: [float];  
}

table Viewport {
  near: [float];  
  far: [float];   
}

table CameraCache {
  view_projection: [units.Matrix4x4];  
}
