namespace q_generated.network;

table ComponentTypeInfo {
  type_id: uint32;
  name: string;
  schema_hash: uint64;
}

table Handshake {
  component_types: [ComponentTypeInfo];
  protocol_version: uint32;
}

table ComponentUpdate {
  type_id: uint32;
  data: [ubyte];
}

table EntityUpdate {
  entity_id: uint32;
  component_updates: [ComponentUpdate];
}

table EntityCreate {
  entity_id: uint32;
  component_type_ids: [uint32];
}

table EntityDestroy {
  entity_id: uint32;
}

union MessagePayload {
  Handshake,
  EntityCreate,
  EntityDestroy,
  EntityUpdate
}

table Message {
  payload: MessagePayload;
  timestamp: uint64;
}

table Batch {
  messages: [Message];
}

root_type Batch;
